import { chromium } from "@playwright/test";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
await page.goto("http://localhost:5173");
await page.locator('nav [data-page="race"]').click();
await page.locator('[data-mode="driver"]').click();
await page.locator('[data-race-type="practice"]').click();
await page.locator('[data-action="start"]').click();
await page.waitForSelector("#race-stage");
await page.waitForFunction(() => !document.querySelector(".countdown"));
await page.locator("#throttle").fill("35");
await page.waitForTimeout(1300);
await page.keyboard.press("c");
await page.waitForTimeout(700);
await page.screenshot({ path: "docs/screenshots/cockpit.png" });
await page.keyboard.press("p");
await page.locator('.modal [data-page="race"]').click();
await page.locator("#track-select").selectOption("7");
await page.locator('[data-action="start"]').click();
await page.waitForSelector("#race-stage");
await page.waitForFunction(() => !document.querySelector(".countdown"));
await page.locator("#throttle").fill("35");
await page.waitForTimeout(1300);
await page.screenshot({ path: "docs/screenshots/night.png" });
console.log("Camera/night render errors", errors);
await browser.close();
