export const presets = [
  {
    name: "The Club Circuit",
    tag: "THE PERFECT ALL-ROUNDER",
    difficulty: "Intermediate",
    description: "Fast straights. Technical corners. Pure slot racing.",
    points: [
      [-12, -6],
      [-3, -6],
      [1, -3],
      [8, -5],
      [13, -2],
      [12, 4],
      [6, 7],
      [-3, 6],
      [-6, 2],
      [-12, 3],
      [-15, 0],
    ],
    bridge: false,
  },
  {
    name: "The Classic Oval",
    tag: "BACK TO WHERE IT STARTED",
    difficulty: "Beginner",
    description: "Two long straights. Two sweeping turns. Endless rivalry.",
    points: [
      [-11, -6],
      [0, -6],
      [11, -6],
      [15, 0],
      [11, 6],
      [0, 6],
      [-11, 6],
      [-15, 0],
    ],
    bridge: false,
  },
  {
    name: "The Crossover",
    tag: "A NEW LEVEL OF RACING",
    difficulty: "Expert",
    description: "A raised crossover and two demanding loops.",
    points: [
      [-13, -6],
      [-6, -7],
      [0, 0],
      [7, 7],
      [13, 5],
      [14, 0],
      [10, -5],
      [5, -5],
      [0, 0],
      [-7, 7],
      [-13, 5],
      [-15, 0],
    ],
    bridge: true,
  },
];
export const cars = [
  {
    id: "porsche",
    name: "Porsche 911 GT3",
    type: "GT SERIES",
    color: "#ff6332",
    speed: 22,
    grip: 24,
    accel: 10,
    year: "2023",
    number: "91",
  },
  {
    id: "ford",
    name: "Ford Mustang GT",
    type: "AMERICAN MUSCLE",
    color: "#76aac1",
    speed: 24,
    grip: 20,
    accel: 9,
    year: "1967",
    number: "07",
  },
  {
    id: "mclaren",
    name: "McLaren 720S",
    type: "SUPERCAR",
    color: "#e6bc35",
    speed: 26,
    grip: 22,
    accel: 11,
    year: "2022",
    number: "04",
  },
  {
    id: "mini",
    name: "Mini Cooper S",
    type: "TOURING CLASSIC",
    color: "#7a9870",
    speed: 19,
    grip: 29,
    accel: 12,
    year: "1965",
    number: "37",
  },
  {
    id: "aston",
    name: "Aston Martin Vantage",
    type: "ENDURANCE GT",
    color: "#27847c",
    speed: 23,
    grip: 26,
    accel: 10,
    year: "2024",
    number: "95",
  },
  {
    id: "bmw",
    name: "BMW M3 E30",
    type: "TOURING LEGEND",
    color: "#e6e0d5",
    speed: 21,
    grip: 27,
    accel: 11,
    year: "1991",
    number: "30",
  },
];
export function stepSpeed(speed, throttle, brake, dt, car) {
  return Math.max(
    0,
    Math.min(
      car.speed,
      speed + (throttle * car.accel - (brake ? 22 : 2.2) - speed * 0.085) * dt,
    ),
  );
}
export function cornerLoad(speed, curvature, grip) {
  return (speed * speed * curvature) / grip;
}
