import { rateCar } from "./economy.js";
import { expandedCars } from "./expanded-cars.js";
export const presets = [
  {
    name: "The Club Circuit",
    tag: "THE PERFECT ALL-ROUNDER",
    difficulty: "Intermediate",
    description: "Fast straights. Technical corners. Pure slot racing.",
    points: [
      [-12, -6],
      [-3, -6],
      [1, -3],
      [8, -5],
      [13, -2],
      [12, 4],
      [6, 7],
      [-3, 6],
      [-6, 2],
      [-12, 3],
      [-15, 0],
    ],
    bridge: false,
  },
  {
    name: "The Classic Oval",
    tag: "BACK TO WHERE IT STARTED",
    difficulty: "Beginner",
    description: "Two long straights. Two sweeping turns. Endless rivalry.",
    points: [
      [-11, -6],
      [0, -6],
      [11, -6],
      [15, 0],
      [11, 6],
      [0, 6],
      [-11, 6],
      [-15, 0],
    ],
    bridge: false,
  },
  {
    name: "The Crossover",
    tag: "A NEW LEVEL OF RACING",
    difficulty: "Expert",
    description: "A raised crossover and two demanding loops.",
    points: [
      [-13, -6],
      [-6, -7],
      [0, 0],
      [7, 7],
      [13, 5],
      [14, 0],
      [10, -5],
      [5, -5],
      [0, 0],
      [-7, 7],
      [-13, 5],
      [-15, 0],
    ],
    bridge: true,
  },
  {
    name: "The Coastal Sprint",
    tag: "LONG STRAIGHTS / WIDE SWEEPERS",
    difficulty: "Beginner",
    description:
      "Open the throttle along the coast, then sweep through wide bends.",
    points: [
      [-15, -7],
      [-3, -8],
      [12, -7],
      [16, -3],
      [14, 4],
      [6, 8],
      [-7, 7],
      [-16, 3],
    ],
    theme: "coast",
  },
  {
    name: "The Grand Prix",
    tag: "THE FULL RACE WEEKEND",
    difficulty: "Intermediate",
    description:
      "A long pit straight, a stadium loop and a flowing technical sector.",
    points: [
      [-16, -8],
      [-5, -8],
      [12, -8],
      [16, -4],
      [13, 0],
      [7, -1],
      [3, 3],
      [11, 5],
      [12, 9],
      [1, 9],
      [-6, 6],
      [-15, 8],
      [-18, 2],
    ],
    theme: "gp",
  },
  {
    name: "The Alpine Pass",
    tag: "CLIMB / DESCEND / REPEAT",
    difficulty: "Expert",
    description:
      "A sweeping elevated ridge, downhill turns and a forest hairpin.",
    points: [
      [-15, -7],
      [-5, -8],
      [6, -6],
      [15, -2],
      [14, 7],
      [7, 8],
      [4, 1],
      [-3, -1],
      [-6, 7],
      [-15, 6],
      [-17, 0],
    ],
    bridge: true,
    heights: [0, 1.3, 3.2, 2, 0, 0, 0, 0, 0, 0, 0],
    theme: "alpine",
  },
  {
    name: "The Endurance Ring",
    tag: "BUILT FOR THE LONG RUN",
    difficulty: "Intermediate",
    description:
      "A fast outer loop and an infield section that rewards a steady hand.",
    points: [
      [-17, -8],
      [-4, -9],
      [13, -8],
      [18, -3],
      [15, 7],
      [8, 9],
      [4, 5],
      [7, 1],
      [1, -2],
      [-6, 1],
      [-5, 7],
      [-14, 8],
      [-18, 2],
    ],
    theme: "endurance",
  },
  {
    name: "The Night Session",
    tag: "AFTER DARK / FULL FOCUS",
    difficulty: "Intermediate",
    description:
      "Floodlit asphalt, glowing pit garages and an electric night atmosphere.",
    points: [
      [-14, -7],
      [0, -8],
      [14, -6],
      [16, 1],
      [11, 7],
      [3, 8],
      [-1, 3],
      [-8, 3],
      [-14, 7],
      [-17, 0],
    ],
    theme: "night",
  },
  {
    name: "The Club Hairpins",
    tag: "PRECISION OVER POWER",
    difficulty: "Expert",
    description:
      "Two tight return bends, short straights and a final sweeping corner.",
    points: [
      [-16, -8],
      [0, -8],
      [15, -7],
      [17, -3],
      [13, 0],
      [4, -2],
      [1, 1],
      [5, 5],
      [13, 4],
      [15, 8],
      [5, 10],
      [-7, 7],
      [-16, 3],
    ],
    theme: "club",
  },
];
export const cars = [
  {
    id: "porsche",
    name: "Porsche 911 GT3 RS",
    type: "GT SERIES",
    color: "#ff6332",
    speed: 22,
    grip: 24,
    accel: 10,
    year: "2023",
    number: "91",
  },
  {
    id: "ford",
    name: "Ford Mustang Mach 1",
    type: "AMERICAN MUSCLE",
    color: "#76aac1",
    speed: 24,
    grip: 20,
    accel: 9,
    year: "1969",
    number: "07",
  },
  {
    id: "mclaren",
    name: "McLaren P1 GTR",
    type: "SUPERCAR",
    color: "#e6bc35",
    speed: 26,
    grip: 22,
    accel: 11,
    year: "2015",
    number: "04",
  },
  {
    id: "mini",
    name: "Mini Cooper S",
    type: "TOURING CLASSIC",
    color: "#7a9870",
    speed: 19,
    grip: 29,
    accel: 12,
    year: "2014",
    number: "37",
  },
  {
    id: "aston",
    modelRotation: Math.PI,
    name: "Aston Martin DB11",
    type: "ENDURANCE GT",
    color: "#27847c",
    speed: 23,
    grip: 26,
    accel: 10,
    year: "2017",
    number: "95",
  },
  {
    id: "bmw",
    name: "BMW M4 Competition",
    type: "TOURING LEGEND",
    color: "#e6e0d5",
    speed: 21,
    grip: 27,
    accel: 11,
    year: "2021",
    number: "30",
  },
  {
    id: "ferrari-f40",
    name: "Ferrari F40",
    type: "POSTER ICON",
    year: "1987",
    speed: 25,
    grip: 23,
    accel: 11,
    color: "#ee623b",
    number: "41",
  },
  {
    id: "lamborghini-countach",
    name: "Lamborghini Countach",
    type: "POSTER ICON",
    year: "1989",
    speed: 24,
    grip: 21,
    accel: 10,
    color: "#e1c47d",
    number: "42",
  },
  {
    id: "lancia-stratos",
    name: "Lancia Stratos HF",
    type: "RALLY LEGEND",
    year: "1974",
    speed: 21,
    grip: 28,
    accel: 12,
    color: "#a3ba8e",
    number: "43",
  },
  {
    id: "audi-sport-quattro",
    name: "Audi Sport Quattro",
    type: "GROUP B",
    year: "1984",
    speed: 22,
    grip: 28,
    accel: 12,
    color: "#ee623b",
    number: "44",
  },
  {
    id: "bmw-m1",
    name: "BMW M1 AHG",
    type: "PROCAR HERO",
    year: "1980",
    speed: 23,
    grip: 25,
    accel: 10,
    color: "#e1c47d",
    number: "45",
  },
  {
    id: "mazda-787b",
    name: "Mazda 787B",
    type: "GROUP C",
    year: "1991",
    speed: 26,
    grip: 26,
    accel: 11,
    color: "#a3ba8e",
    number: "46",
  },
  {
    id: "toyota-supra-a80",
    name: "Toyota Supra A80",
    type: "JAPANESE ICON",
    year: "1993",
    speed: 24,
    grip: 24,
    accel: 11,
    color: "#ee623b",
    number: "47",
  },
  {
    id: "honda-nsx-r",
    name: "Honda NSX-R",
    type: "JAPANESE ICON",
    year: "1992",
    speed: 23,
    grip: 28,
    accel: 11,
    color: "#e1c47d",
    number: "48",
  },
  {
    id: "jaguar-xj220",
    name: "Jaguar XJ220",
    type: "SUPERCAR",
    year: "1992",
    speed: 26,
    grip: 23,
    accel: 10,
    color: "#a3ba8e",
    number: "49",
  },
  {
    id: "mercedes-300sl",
    name: "Mercedes-Benz 300 SL",
    type: "GULLWING CLASSIC",
    year: "1954",
    speed: 20,
    grip: 23,
    accel: 9,
    color: "#ee623b",
    number: "50",
  },
  {
    id: "vw-golf-gti-mk1",
    name: "Volkswagen Golf GTI",
    type: "HOT HATCH",
    year: "1976",
    speed: 19,
    grip: 29,
    accel: 12,
    color: "#e1c47d",
    number: "51",
  },
  {
    id: "porsche-930",
    name: "Porsche 930 Turbo",
    type: "TURBO CLASSIC",
    year: "1975",
    speed: 23,
    grip: 21,
    accel: 10,
    color: "#a3ba8e",
    number: "52",
  },
  {
    id: "lotus-esprit-v8",
    name: "Lotus Esprit V8",
    type: "BRITISH EXOTIC",
    year: "1996",
    speed: 24,
    grip: 25,
    accel: 11,
    color: "#ee623b",
    number: "53",
  },
  {
    id: "ferrari-250-gto",
    name: "Ferrari 250 GTO",
    type: "ENDURANCE CLASSIC",
    year: "1962",
    speed: 22,
    grip: 24,
    accel: 10,
    color: "#e1c47d",
    number: "54",
  },
  ...expandedCars,
].map(rateCar);
export function stepSpeed(speed, throttle, brake, dt, car) {
  const target = brake ? 0 : Math.max(0, Math.min(1, throttle)) * car.speed;
  const rate =
    target > speed
      ? car.accel * (0.35 + 0.65 * throttle)
      : brake
        ? car.braking || 28
        : 10;
  return Math.max(
    0,
    Math.min(
      car.speed,
      speed +
        Math.sign(target - speed) *
          Math.min(Math.abs(target - speed), rate * dt),
    ),
  );
}
export function cornerLoad(speed, curvature, grip) {
  return (speed * speed * curvature) / (grip * 2.8);
}
