// Catalogue names and asset provenance: public/models/credits.json.
export const expandedCars = [
  {
    id: "aston-martin-one-77",
    name: "Aston Martin One-77",
    type: "MODERN ICON",
    year: "2009",
    color: "#ee623b",
    number: "55",
    sharedModel: true,
  },
  {
    id: "aston-martin-valiant",
    name: "Aston Martin Valiant",
    type: "MODERN ICON",
    year: "2025",
    color: "#ee623b",
    number: "56",
    sharedModel: true,
  },
  {
    id: "audi-r15-tdi",
    name: "Audi R15 TDI",
    type: "MODERN ICON",
    year: "2009",
    color: "#ee623b",
    number: "57",
    sharedModel: true,
  },
  {
    id: "audi-r18",
    name: "Audi R18",
    type: "MODERN ICON",
    year: "2011",
    color: "#ee623b",
    number: "58",
    sharedModel: true,
  },
  {
    id: "audi-r8-gt-2011",
    name: "Audi R8 GT",
    type: "MODERN ICON",
    year: "2011",
    color: "#ee623b",
    number: "59",
    sharedModel: true,
  },
  {
    id: "audi-r8-v10-gt",
    name: "Audi R8 V10 GT RWD",
    type: "MODERN ICON",
    year: "2023",
    color: "#ee623b",
    number: "60",
    sharedModel: true,
  },
  {
    id: "audi-rs-etron-gt",
    name: "Audi RS e-tron GT",
    type: "MODERN ICON",
    year: "2022",
    color: "#ee623b",
    number: "61",
    sharedModel: true,
  },
  {
    id: "audi-rs6-avant-gt",
    name: "Audi RS 6 Avant GT",
    type: "MODERN ICON",
    year: "2024",
    color: "#ee623b",
    number: "62",
    sharedModel: true,
  },
  {
    id: "audi-ur-quattro",
    name: "Audi quattro",
    type: "HERITAGE",
    year: "1980",
    color: "#ee623b",
    number: "63",
    sharedModel: true,
  },
  {
    id: "bac-mono",
    name: "BAC Mono",
    type: "MODERN ICON",
    year: "2017",
    color: "#ee623b",
    number: "64",
    sharedModel: true,
  },
  {
    id: "bmw-30-csl",
    name: "BMW 3.0 CSL",
    type: "HERITAGE",
    year: "1973",
    color: "#ee623b",
    number: "65",
    sharedModel: true,
  },
  {
    id: "bmw-i8-roadster",
    name: "BMW i8 Roadster",
    type: "MODERN ICON",
    year: "2019",
    color: "#ee623b",
    number: "66",
    sharedModel: true,
  },
  {
    id: "bmw-m2-g87",
    name: "BMW M2 (G87)",
    type: "MODERN ICON",
    year: "2023",
    color: "#ee623b",
    number: "67",
    sharedModel: true,
  },
  {
    id: "bmw-m3-csl-e46",
    name: "BMW M3 CSL",
    type: "MODERN ICON",
    year: "2003",
    color: "#ee623b",
    number: "68",
    sharedModel: true,
  },
  {
    id: "bmw-m3-e30",
    name: "BMW M3",
    type: "HERITAGE",
    year: "1986",
    color: "#ee623b",
    number: "69",
    sharedModel: true,
  },
  {
    id: "bmw-m3-e36",
    name: "BMW M3 (E36)",
    type: "HERITAGE",
    year: "1993",
    color: "#ee623b",
    number: "70",
    sharedModel: true,
  },
  {
    id: "bmw-m3-e46",
    name: "BMW M3 (E46)",
    type: "MODERN ICON",
    year: "2003",
    color: "#ee623b",
    number: "71",
    sharedModel: true,
  },
  {
    id: "bmw-m3-gts-e92",
    name: "BMW M3 GTS",
    type: "MODERN ICON",
    year: "2011",
    color: "#ee623b",
    number: "72",
    sharedModel: true,
  },
  {
    id: "bmw-m4-f82",
    name: "BMW M4 (F82)",
    type: "MODERN ICON",
    year: "2018",
    color: "#ee623b",
    number: "73",
    sharedModel: true,
  },
  {
    id: "bmw-m4-g82",
    name: "BMW M4 Competition (G82)",
    type: "MODERN ICON",
    year: "2021",
    color: "#ee623b",
    number: "74",
    sharedModel: true,
  },
  {
    id: "bmw-m5-competition",
    name: "BMW M5 Competition",
    type: "MODERN ICON",
    year: "2021",
    color: "#ee623b",
    number: "75",
    sharedModel: true,
  },
  {
    id: "bugatti-bolide",
    name: "Bugatti Bolide",
    type: "MODERN ICON",
    year: "2020",
    color: "#ee623b",
    number: "76",
    sharedModel: true,
  },
  {
    id: "bugatti-chiron",
    name: "Bugatti Chiron Pur Sport",
    type: "MODERN ICON",
    year: "2021",
    color: "#ee623b",
    number: "77",
    sharedModel: true,
  },
  {
    id: "bugatti-divo",
    name: "Bugatti Divo",
    type: "MODERN ICON",
    year: "2019",
    color: "#ee623b",
    number: "78",
    sharedModel: true,
  },
  {
    id: "bugatti-tourbillon",
    name: "Bugatti Tourbillon",
    type: "MODERN ICON",
    year: "2026",
    color: "#ee623b",
    number: "79",
    sharedModel: true,
  },
  {
    id: "bugatti-veyron",
    name: "Bugatti Veyron 16.4",
    type: "MODERN ICON",
    year: "2005",
    color: "#ee623b",
    number: "80",
    sharedModel: true,
  },
  {
    id: "ferrari-12cilindri",
    name: "Ferrari 12Cilindri",
    type: "MODERN ICON",
    year: "2025",
    color: "#ee623b",
    number: "81",
    sharedModel: true,
  },
  {
    id: "ferrari-296-gts",
    name: "Ferrari 296 GTS",
    type: "MODERN ICON",
    year: "2023",
    color: "#ee623b",
    number: "82",
    sharedModel: true,
  },
  {
    id: "ferrari-430-scuderia",
    name: "Ferrari 430 Scuderia",
    type: "MODERN ICON",
    year: "2008",
    color: "#ee623b",
    number: "83",
    sharedModel: true,
  },
  {
    id: "ferrari-488-pista",
    name: "Ferrari 488 Pista",
    type: "MODERN ICON",
    year: "2019",
    color: "#ee623b",
    number: "84",
    sharedModel: true,
  },
  {
    id: "ferrari-599-gto",
    name: "Ferrari 599 GTO",
    type: "MODERN ICON",
    year: "2010",
    color: "#ee623b",
    number: "85",
    sharedModel: true,
  },
  {
    id: "ferrari-849-testarossa",
    name: "Ferrari 849 Testarossa",
    type: "MODERN ICON",
    year: "2026",
    color: "#ee623b",
    number: "86",
    sharedModel: true,
  },
  {
    id: "ferrari-enzo",
    name: "Ferrari Enzo",
    type: "MODERN ICON",
    year: "2002",
    color: "#ee623b",
    number: "87",
    sharedModel: true,
  },
  {
    id: "ferrari-f50",
    name: "Ferrari F50",
    type: "HERITAGE",
    year: "1995",
    color: "#ee623b",
    number: "88",
    sharedModel: true,
  },
  {
    id: "ferrari-f8-tributo",
    name: "Ferrari F8 Tributo",
    type: "MODERN ICON",
    year: "2020",
    color: "#ee623b",
    number: "89",
    sharedModel: true,
  },
  {
    id: "ferrari-laferrari",
    name: "Ferrari LaFerrari",
    type: "MODERN ICON",
    year: "2013",
    color: "#ee623b",
    number: "90",
    sharedModel: true,
  },
  {
    id: "ferrari-monza-sp2",
    name: "Ferrari Monza SP2",
    type: "MODERN ICON",
    year: "2019",
    color: "#ee623b",
    number: "91",
    sharedModel: true,
  },
  {
    id: "ferrari-sf90-xx",
    name: "Ferrari SF90 XX Stradale",
    type: "MODERN ICON",
    year: "2023",
    color: "#ee623b",
    number: "92",
    sharedModel: true,
  },
  {
    id: "glickenhaus-scg-004c",
    name: "Glickenhaus SCG 004C",
    type: "MODERN ICON",
    year: "2020",
    color: "#ee623b",
    number: "93",
    sharedModel: true,
  },
  {
    id: "honda-civic-type-r-ek9",
    name: "Honda Civic Type R (EK9)",
    type: "MODERN ICON",
    year: "2000",
    color: "#ee623b",
    number: "94",
    sharedModel: true,
  },
  {
    id: "honda-civic-type-r-fk2",
    name: "Honda Civic Type R (FK2)",
    type: "MODERN ICON",
    year: "2015",
    color: "#ee623b",
    number: "95",
    sharedModel: true,
  },
  {
    id: "honda-civic-type-r-fk8",
    name: "Honda Civic Type R (FK8)",
    type: "MODERN ICON",
    year: "2018",
    color: "#ee623b",
    number: "96",
    sharedModel: true,
  },
  {
    id: "honda-civic-type-r-fl5",
    name: "Honda Civic Type R (FL5)",
    type: "MODERN ICON",
    year: "2023",
    color: "#ee623b",
    number: "97",
    sharedModel: true,
  },
  {
    id: "honda-crx",
    name: "Honda CR-X",
    type: "HERITAGE",
    year: "1988",
    color: "#ee623b",
    number: "98",
    sharedModel: true,
  },
  {
    id: "honda-integra-dc2",
    name: "Honda Integra Type R (DC2)",
    type: "HERITAGE",
    year: "1998",
    color: "#ee623b",
    number: "99",
    sharedModel: true,
  },
  {
    id: "honda-integra-dc5",
    name: "Honda Integra Type R (DC5)",
    type: "MODERN ICON",
    year: "2001",
    color: "#ee623b",
    number: "100",
    sharedModel: true,
  },
  {
    id: "honda-s800",
    name: "Honda S800",
    type: "HERITAGE",
    year: "1966",
    color: "#ee623b",
    number: "101",
    sharedModel: true,
  },
  {
    id: "jaguar-xkr",
    name: "Jaguar XKR 5.0 Supercharged Speed Pack",
    type: "MODERN ICON",
    year: "2009",
    color: "#ee623b",
    number: "102",
    sharedModel: true,
  },
  {
    id: "koenigsegg-agera-rs",
    name: "Koenigsegg Agera RS",
    type: "MODERN ICON",
    year: "2015",
    color: "#ee623b",
    number: "103",
    sharedModel: true,
  },
  {
    id: "koenigsegg-ccx",
    name: "Koenigsegg CCX",
    type: "MODERN ICON",
    year: "2006",
    color: "#ee623b",
    number: "104",
    sharedModel: true,
  },
  {
    id: "koenigsegg-jesko",
    name: "Koenigsegg Jesko",
    type: "MODERN ICON",
    year: "2020",
    color: "#ee623b",
    number: "105",
    sharedModel: true,
  },
  {
    id: "koenigsegg-one",
    name: "Koenigsegg One:1",
    type: "MODERN ICON",
    year: "2014",
    color: "#ee623b",
    number: "106",
    sharedModel: true,
  },
  {
    id: "lamborghini-aventador",
    name: "Lamborghini Aventador LP700-4",
    type: "MODERN ICON",
    year: "2011",
    color: "#ee623b",
    number: "107",
    sharedModel: true,
  },
  {
    id: "lamborghini-centenario",
    name: "Lamborghini Centenario",
    type: "MODERN ICON",
    year: "2016",
    color: "#ee623b",
    number: "108",
    sharedModel: true,
  },
  {
    id: "lamborghini-gallardo",
    name: "Lamborghini Gallardo LP560-4",
    type: "MODERN ICON",
    year: "2010",
    color: "#ee623b",
    number: "109",
    sharedModel: true,
  },
  {
    id: "lamborghini-huracan-sterrato",
    name: "Lamborghini Huracán Sterrato",
    type: "MODERN ICON",
    year: "2023",
    color: "#ee623b",
    number: "110",
    sharedModel: true,
  },
  {
    id: "lamborghini-reventon",
    name: "Lamborghini Reventón",
    type: "MODERN ICON",
    year: "2008",
    color: "#ee623b",
    number: "111",
    sharedModel: true,
  },
  {
    id: "lamborghini-revuelto",
    name: "Lamborghini Revuelto",
    type: "MODERN ICON",
    year: "2024",
    color: "#ee623b",
    number: "112",
    sharedModel: true,
  },
  {
    id: "lamborghini-sian",
    name: "Lamborghini Sián Roadster",
    type: "MODERN ICON",
    year: "2021",
    color: "#ee623b",
    number: "113",
    sharedModel: true,
  },
  {
    id: "lamborghini-temerario",
    name: "Lamborghini Temerario",
    type: "MODERN ICON",
    year: "2025",
    color: "#ee623b",
    number: "114",
    sharedModel: true,
  },
  {
    id: "lamborghini-veneno",
    name: "Lamborghini Veneno",
    type: "MODERN ICON",
    year: "2013",
    color: "#ee623b",
    number: "115",
    sharedModel: true,
  },
  {
    id: "lancia-037",
    name: "Lancia Rally 037",
    type: "HERITAGE",
    year: "1982",
    color: "#ee623b",
    number: "116",
    sharedModel: true,
  },
  {
    id: "lancia-delta-integrale",
    name: "Lancia Delta HF Integrale Evoluzione",
    type: "HERITAGE",
    year: "1992",
    color: "#ee623b",
    number: "117",
    sharedModel: true,
  },
  {
    id: "lexus-lfa-nurburgring",
    name: "Lexus LFA Nürburgring Package",
    type: "MODERN ICON",
    year: "2012",
    color: "#ee623b",
    number: "118",
    sharedModel: true,
  },
  {
    id: "lexus-lfa",
    name: "Lexus LFA",
    type: "MODERN ICON",
    year: "2011",
    color: "#ee623b",
    number: "119",
    sharedModel: true,
  },
  {
    id: "lotus-3-eleven",
    name: "Lotus 3-Eleven",
    type: "MODERN ICON",
    year: "2015",
    color: "#ee623b",
    number: "120",
    sharedModel: true,
  },
  {
    id: "lotus-elise-sprint",
    name: "Lotus Elise Sprint 220",
    type: "MODERN ICON",
    year: "2018",
    color: "#ee623b",
    number: "121",
    sharedModel: true,
  },
  {
    id: "lotus-emira",
    name: "Lotus Emira Turbo SE",
    type: "MODERN ICON",
    year: "2023",
    color: "#ee623b",
    number: "122",
    sharedModel: true,
  },
  {
    id: "lotus-evora-gt430",
    name: "Lotus Evora GT430",
    type: "MODERN ICON",
    year: "2018",
    color: "#ee623b",
    number: "123",
    sharedModel: true,
  },
  {
    id: "lotus-evora-s",
    name: "Lotus Evora S",
    type: "MODERN ICON",
    year: "2010",
    color: "#ee623b",
    number: "124",
    sharedModel: true,
  },
  {
    id: "lotus-exige-240",
    name: "Lotus Exige S 240",
    type: "MODERN ICON",
    year: "2008",
    color: "#ee623b",
    number: "125",
    sharedModel: true,
  },
  {
    id: "lotus-exige-360-cup",
    name: "Lotus Exige 360 Cup",
    type: "MODERN ICON",
    year: "2016",
    color: "#ee623b",
    number: "126",
    sharedModel: true,
  },
  {
    id: "lotus-exige-s-2006",
    name: "Lotus Exige S",
    type: "MODERN ICON",
    year: "2006",
    color: "#ee623b",
    number: "127",
    sharedModel: true,
  },
  {
    id: "maserati-mc12",
    name: "Maserati MC12 Stradale",
    type: "MODERN ICON",
    year: "2004",
    color: "#ee623b",
    number: "128",
    sharedModel: true,
  },
  {
    id: "maserati-mc20",
    name: "Maserati MC20",
    type: "MODERN ICON",
    year: "2021",
    color: "#ee623b",
    number: "129",
    sharedModel: true,
  },
  {
    id: "mclaren-600lt",
    name: "McLaren 600LT",
    type: "MODERN ICON",
    year: "2018",
    color: "#ee623b",
    number: "130",
    sharedModel: true,
  },
  {
    id: "mclaren-675lt-spider",
    name: "McLaren 675LT Spider",
    type: "MODERN ICON",
    year: "2016",
    color: "#ee623b",
    number: "131",
    sharedModel: true,
  },
  {
    id: "mclaren-765lt",
    name: "McLaren 765LT",
    type: "MODERN ICON",
    year: "2020",
    color: "#ee623b",
    number: "132",
    sharedModel: true,
  },
  {
    id: "mclaren-artura",
    name: "McLaren Artura",
    type: "MODERN ICON",
    year: "2023",
    color: "#ee623b",
    number: "133",
    sharedModel: true,
  },
  {
    id: "mclaren-f1-lm",
    name: "McLaren F1 LM",
    type: "HERITAGE",
    year: "1995",
    color: "#ee623b",
    number: "134",
    sharedModel: true,
  },
  {
    id: "mclaren-f1",
    name: "McLaren F1",
    type: "HERITAGE",
    year: "1992",
    color: "#ee623b",
    number: "135",
    sharedModel: true,
  },
  {
    id: "mclaren-mp4-12c",
    name: "McLaren MP4-12C",
    type: "MODERN ICON",
    year: "2011",
    color: "#ee623b",
    number: "136",
    sharedModel: true,
  },
  {
    id: "mclaren-senna",
    name: "McLaren Senna",
    type: "MODERN ICON",
    year: "2018",
    color: "#ee623b",
    number: "137",
    sharedModel: true,
  },
  {
    id: "mclaren-solus-gt",
    name: "McLaren Solus GT",
    type: "MODERN ICON",
    year: "2023",
    color: "#ee623b",
    number: "138",
    sharedModel: true,
  },
  {
    id: "mclaren-speedtail",
    name: "McLaren Speedtail",
    type: "MODERN ICON",
    year: "2020",
    color: "#ee623b",
    number: "139",
    sharedModel: true,
  },
  {
    id: "mclaren-w1",
    name: "McLaren W1",
    type: "MODERN ICON",
    year: "2025",
    color: "#ee623b",
    number: "140",
    sharedModel: true,
  },
  {
    id: "mercedes-amg-one",
    name: "Mercedes-AMG ONE",
    type: "MODERN ICON",
    year: "2023",
    color: "#ee623b",
    number: "141",
    sharedModel: true,
  },
  {
    id: "mercedes-slr-mclaren",
    name: "Mercedes-Benz SLR McLaren",
    type: "MODERN ICON",
    year: "2004",
    color: "#ee623b",
    number: "142",
    sharedModel: true,
  },
  {
    id: "mini-cooper-s-classic",
    name: "Austin Mini Cooper S",
    type: "HERITAGE",
    year: "1965",
    color: "#ee623b",
    number: "143",
    sharedModel: true,
  },
  {
    id: "mini-jcw-cabrio",
    name: "Mini John Cooper Works Cabrio",
    type: "MODERN ICON",
    year: "2016",
    color: "#ee623b",
    number: "144",
    sharedModel: true,
  },
  {
    id: "mini-jcw-gp",
    name: "Mini John Cooper Works GP",
    type: "MODERN ICON",
    year: "2020",
    color: "#ee623b",
    number: "145",
    sharedModel: true,
  },
  {
    id: "noble-m600",
    name: "Noble M600",
    type: "MODERN ICON",
    year: "2010",
    color: "#ee623b",
    number: "146",
    sharedModel: true,
  },
  {
    id: "pagani-zonda-f",
    name: "Pagani Zonda F",
    type: "MODERN ICON",
    year: "2005",
    color: "#ee623b",
    number: "147",
    sharedModel: true,
  },
  {
    id: "peugeot-9x8",
    name: "Peugeot 9X8 Evo",
    type: "MODERN ICON",
    year: "2024",
    color: "#ee623b",
    number: "148",
    sharedModel: true,
  },
  {
    id: "porsche-911-dakar",
    name: "Porsche 911 Dakar",
    type: "MODERN ICON",
    year: "2023",
    color: "#ee623b",
    number: "149",
    sharedModel: true,
  },
  {
    id: "porsche-959",
    name: "Porsche 959",
    type: "HERITAGE",
    year: "1986",
    color: "#ee623b",
    number: "150",
    sharedModel: true,
  },
  {
    id: "porsche-963",
    name: "Porsche 963",
    type: "MODERN ICON",
    year: "2023",
    color: "#ee623b",
    number: "151",
    sharedModel: true,
  },
  {
    id: "porsche-carrera-gt",
    name: "Porsche Carrera GT",
    type: "MODERN ICON",
    year: "2004",
    color: "#ee623b",
    number: "152",
    sharedModel: true,
  },
  {
    id: "porsche-gt3-992",
    name: "Porsche 911 GT3",
    type: "MODERN ICON",
    year: "2022",
    color: "#ee623b",
    number: "153",
    sharedModel: true,
  },
  {
    id: "rimac-nevera-r",
    name: "Rimac Nevera R",
    type: "MODERN ICON",
    year: "2025",
    color: "#ee623b",
    number: "154",
    sharedModel: true,
  },
  {
    id: "toyota-ae86",
    name: "Toyota Sprinter Trueno (AE86)",
    type: "HERITAGE",
    year: "1985",
    color: "#ee623b",
    number: "155",
    sharedModel: true,
  },
  {
    id: "toyota-gr-supra",
    name: "Toyota GR Supra (A90)",
    type: "MODERN ICON",
    year: "2019",
    color: "#ee623b",
    number: "156",
    sharedModel: true,
  },
  {
    id: "toyota-gr-yaris",
    name: "Toyota GR Yaris",
    type: "MODERN ICON",
    year: "2021",
    color: "#ee623b",
    number: "157",
    sharedModel: true,
  },
  {
    id: "toyota-ts030",
    name: "Toyota TS030 Hybrid",
    type: "MODERN ICON",
    year: "2012",
    color: "#ee623b",
    number: "158",
    sharedModel: true,
  },
  {
    id: "tvr-sagaris",
    name: "TVR Sagaris",
    type: "MODERN ICON",
    year: "2006",
    color: "#ee623b",
    number: "159",
    sharedModel: true,
  },
  {
    id: "vw-beetle",
    name: "Volkswagen Beetle",
    type: "HERITAGE",
    year: "1968",
    color: "#ee623b",
    number: "160",
    sharedModel: true,
  },
  {
    id: "vw-idr",
    name: "Volkswagen ID.R",
    type: "MODERN ICON",
    year: "2018",
    color: "#ee623b",
    number: "161",
    sharedModel: true,
  },
  {
    id: "vw-w12-concept",
    name: "Volkswagen W12 Concept",
    type: "HERITAGE",
    year: "1997",
    color: "#ee623b",
    number: "162",
    sharedModel: true,
  },
  {
    id: "one1",
    name: "Koenigsegg One:1",
    type: "MODERN ICON",
    year: "2014",
    color: "#ee623b",
    number: "163",
    sharedModel: true,
  },
  {
    id: "imola",
    name: "Pagani Imola",
    type: "MODERN ICON",
    year: "2021",
    color: "#ee623b",
    number: "164",
    sharedModel: true,
  },
  {
    id: "caspita",
    name: "Jiotto Caspita",
    type: "HERITAGE",
    year: "1989",
    color: "#ee623b",
    number: "165",
    sharedModel: true,
  },
  {
    id: "f1",
    name: "McLaren F1 GTR Longtail",
    type: "MODERN ICON",
    year: "—",
    color: "#ee623b",
    number: "166",
    sharedModel: true,
  },
  {
    id: "amggt3",
    name: "Mercedes-AMG GT3",
    type: "MODERN ICON",
    year: "—",
    color: "#ee623b",
    number: "167",
    sharedModel: true,
  },
];
